#-------------------------------
# General Site Settings

title: henzoLab
description: The Software Delivery Lab
email: henzolab@gmail.com
phone: '+25451619437/+254705883334'
location: 'Nairobi, Kenya'
privacy: Privacy
